### ISSUE TITLE
0 0 0 0 hmmm array assending ????

### ISSUE THREAD

**Issue by toniminh161200** [thoaikhoa14402/Be_week4#2]
https://github.com/thoaikhoa14402/Be_week4/blob/3215521163a253c1e698f919e277b6935943111a/Check_Ascending_Array.cpp#L27
![image](https://user-images.githubusercontent.com/52942703/112715208-b6dbb480-8f11-11eb-9f6e-821d34e9ba66.png)

**Comment by thoaikhoa14402** [comment]
bool isAscending(int a[100], int n)
{
	// vòng for đầu để kiểm tra mảng có chứa toàn phần tử giống nhau hay không
	int count = 0;
	for (int i = 0; i < n - 1; i++) {
		if (a[i] == a[i + 1]) ++count;
	}
	if (count == n - 1) return false;
	for (int i = 0; i < n - 1; i++)
	{
		for (int j = i + 1; j < n; j++)
			if (a[i] > a[j]) return false;
	}
	return true;
}

**Comment by thoaikhoa14402** [comment]
em sửa lại code ạ, em bổ sung thêm vòng for để kiểm tra coi mảng có phải chứa toàn số giống nhau hay không nếu có thì return false luôn
