### ISSUE TITLE
Dư thừa gì vậy bạn ?

### ISSUE THREAD

**Issue by toniminh161200** [thoaikhoa14402/Be_week4#4]
https://github.com/thoaikhoa14402/Be_week4/blob/3215521163a253c1e698f919e277b6935943111a/L%C3%BD%20thuy%E1%BA%BFt.txt#L8

**Comment by thoaikhoa14402** [comment]
dạ ý là dư thừa vùng nhớ ==> lãng phí tài nguyên ạ
