### ISSUE TITLE
Really a[0] - address of variable a ????

### ISSUE THREAD

**Issue by toniminh161200** [thoaikhoa14402/Be_week4#6]
https://github.com/thoaikhoa14402/Be_week4/blob/3215521163a253c1e698f919e277b6935943111a/L%C3%BD%20thuy%E1%BA%BFt.txt#L17

**Comment by thoaikhoa14402** [comment]
địa chỉ của mảng a là phần tử đầu tiên, tức là địa chỉ của a[0] ạ

**Comment by toniminh161200** [comment]
https://stackoverflow.com/questions/33647319/does-the-address-of-the-array-equal-to-that-of-its-first-element-in-c
Cũng chưa hẳn đâu bạn thử đọc thêm ở bài viết này xem

**Comment by thoaikhoa14402** [comment]
Ý em là a là địa chỉ của phần tử đầu tiên trong mảng a. 
![image](https://user-images.githubusercontent.com/81000230/112718280-8d785400-8f24-11eb-8a97-8b7477cca293.png)

**Comment by thoaikhoa14402** [comment]
Tức là con trỏ trỏ tới cái mảng a, là nó trỏ tới địa chỉ của phần tử đầu tiên trong mảng

**Comment by toniminh161200** [comment]
Ok đó là cái mình muốn bạn hiểu kẻo sau này đi interview gặp mấy câu tưởng dễ nhưng cũng phải hiểu rõ bản chất
